---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	classifier(classifier)
	planner(planner)
	validation(validation)
	experiment(experiment)
	funnel(funnel)
	knowledge_base(knowledge_base)
	decision(decision)
	__end__([<p>__end__</p>]):::last
	__start__ --> classifier;
	classifier --> planner;
	experiment --> decision;
	funnel -.-> decision;
	funnel -.-> validation;
	knowledge_base --> decision;
	planner -.-> funnel;
	planner -.-> knowledge_base;
	planner -.-> validation;
	validation -.-> decision;
	validation -.-> experiment;
	decision --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
